name: Run Gradle
on: push
jobs:
  gradle:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Setup Gradle
      uses: DRSchlaubi/gradle-build-action@feature/annotations
      with:
        arguments: build
